// src/site/site.tsx — the real website: one shell (nav · footer · CTA band · honesty strip), one page anatomy, and a page per topic.
// Every page opens with a live window of the product (see windows.tsx). Links are relative to <base href> so clean URLs work on Pages.
import { useEffect, useRef, useState, type ReactNode } from "react";
import { ReadyIQWebsite, IntegrationHub } from "../v11-page";
import { ConsentBlock } from "../screens/consumer";
import { ScoreWindow, LinkWindow, BoardWindow, FeedWindow, EventsWindow, PassportWindow, DoorWindow, AskWindow, ProtectWindow, BuildWindow, TriWindow, Frame } from "./windows";

type Route = string;
const DEMO = "demo/";

/* ---------- shell ---------- */
function Brand() { return <a className="brand-mark site-brand" href="./"><span className="brand-symbol"><i />R</span><span>Ready<span>IQ</span></span></a>; }

export function SiteNav({ route }: { route: Route }) {
  const [open, setOpen] = useState(false); const [dd, setDd] = useState<string | null>(null); const closeT = useRef<number | null>(null);
  const show = (k: string) => { if (closeT.current) { clearTimeout(closeT.current); closeT.current = null; } setDd(k); };
  const hideSoon = () => { if (closeT.current) clearTimeout(closeT.current); closeT.current = window.setTimeout(() => setDd(null), 450); };
  useEffect(() => { const onDoc = (e: MouseEvent) => { if (!(e.target as HTMLElement).closest(".dd")) setDd(null); }; document.addEventListener("click", onDoc); return () => document.removeEventListener("click", onDoc); }, []);
  const is = (r: string) => route === r || route.startsWith(r + "/");
  const products: [string, string][] = [["products/check/", "Check — three bureaus, honest FICO®"], ["products/dispute-hub/", "Dispute Hub — by bureau, one item at a time"], ["products/build-report/", "Build & report — rent and everyday bills"], ["products/protect-mode/", "Protect Mode — during the loan"], ["products/passport/", "Readiness Passport — a status you own"], ["products/ask/", "Ask ReadyIQ — the underwriter in your pocket"]];
  const who: [string, string][] = [["loan-officers/", "Loan officers — one link, status only"], ["consumers/", "Consumers — check, build, dispute"], ["partners/", "Partners — realtors and buildings"]];
  return <header className={`site-nav ${open ? "open" : ""}`}>
    <div className="site-nav-inner">
      <Brand />
      <nav className="site-links">
        <a href="platform/" className={is("platform") ? "on" : ""}>Platform</a>
        <div className={`dd ${dd === "p" ? "show" : ""}`} onMouseEnter={() => show("p")} onMouseLeave={hideSoon}><button className={is("products") ? "on" : ""} onClick={() => (dd === "p" ? setDd(null) : show("p"))}>Products ▾</button><div className="dd-menu"><div className="dd-box">{products.map(([h, l]) => <a key={h} href={h}>{l}</a>)}</div></div></div>
        <div className={`dd ${dd === "w" ? "show" : ""}`} onMouseEnter={() => show("w")} onMouseLeave={hideSoon}><button className={is("loan-officers") || is("consumers") || is("partners") ? "on" : ""} onClick={() => (dd === "w" ? setDd(null) : show("w"))}>Who it’s for ▾</button><div className="dd-menu"><div className="dd-box">{who.map(([h, l]) => <a key={h} href={h}>{l}</a>)}</div></div></div>
        <a href="integrations/" className={is("integrations") ? "on" : ""}>Integrations</a>
        <a href="trust/" className={is("trust") ? "on" : ""}>Trust</a>
        <a href="resources/" className={is("resources") ? "on" : ""}>Resources</a>
      </nav>
      <div className="site-actions"><a className="site-try" href={DEMO + "?mode=consumer&cpage=result"}>Try the live demo</a><a className="site-signin" href="sign-in/">Sign in</a><a className="site-demo" href="book-a-demo/">Book a demo <span>↗</span></a><button className="site-burger" onClick={() => setOpen(!open)} aria-label="Menu">☰</button></div>
    </div>
    {open && <div className="site-mobile"><a href="platform/">Platform</a>{products.map(([h, l]) => <a key={h} href={h}>{l.split(" — ")[0]}</a>)}{who.map(([h, l]) => <a key={h} href={h}>{l.split(" — ")[0]}</a>)}<a href="integrations/">Integrations</a><a href="trust/">Trust</a><a href="resources/">Resources</a><a href="sign-in/">Sign in</a><a href="book-a-demo/">Book a demo</a><a href={DEMO + "?mode=consumer&cpage=result"}>Try the live demo</a></div>}
  </header>;
}

export function HonestyStrip() {
  return <div className="honesty"><span>✓ Status, never reports</span><span>✓ No promised deletions, points or approvals</span><span>✓ Soft pull only — apply at any time, never required</span><span>✓ MyScoreIQ + CreditBuilderIQ, named on every screen</span></div>;
}

export function CtaBand({ title = <>Give every “not yet” a <em>path back to you.</em></>, sub = "One link per loan officer. A front door for every consumer. Status into the CRM you already run." }: { title?: ReactNode; sub?: string }) {
  return <section className="cta-band"><div><span className="section-kicker light">READY WHEN YOU ARE</span><h2>{title}</h2><p>{sub}</p></div><div className="cta-band-actions"><a className="b2b-primary" href={DEMO + "?mode=lender&lpage=start"}>Get your link in 60 seconds →</a><a className="cta-ghost" href="book-a-demo/">Book a demo</a></div></section>;
}

export function SiteFooter() {
  const col = (t: string, links: [string, string][]) => <div><strong>{t}</strong>{links.map(([h, l]) => <a key={h} href={h}>{l}</a>)}</div>;
  return <footer className="site-footer">
    <div className="site-footer-inner">
      <div className="site-footer-brand"><Brand /><p>A lender-owned credit-readiness platform on IDIQ’s MyScoreIQ and CreditBuilderIQ. Not a CRM, on purpose.</p><small>Consumer credit tools — not a mortgage approval or lending decision. You can apply for a mortgage at any time; this is not required.</small></div>
      {col("Platform", [["platform/", "How it works"], ["integrations/", "Integrations"], ["trust/", "Trust & compliance"], [DEMO + "?guide=1", "The eight leader moves"]])}
      {col("Products", [["products/check/", "Check"], ["products/dispute-hub/", "Dispute Hub"], ["products/build-report/", "Build & report"], ["products/protect-mode/", "Protect Mode"], ["products/passport/", "Readiness Passport"], ["products/ask/", "Ask ReadyIQ"]])}
      {col("Who it’s for", [["loan-officers/", "Loan officers"], ["consumers/", "Consumers"], ["partners/", "Partners"], ["resources/", "Resources & FAQ"], ["book-a-demo/", "Book a demo"], ["sign-in/", "Sign in"]])}
    </div>
    <div className="site-footer-legal"><span>© 2026 ReadyIQ · a product of IDIQ</span><span>MyScoreIQ® · CreditBuilderIQ® · FICO® is a registered trademark of Fair Isaac Corporation</span><span>English · Español</span></div>
  </footer>;
}

/* ---------- page anatomy ---------- */
type Layout = "split" | "rev" | "center" | "narrow" | "band" | "grid";
type Section = { kicker: string; title: ReactNode; body: ReactNode; aside?: ReactNode; dark?: boolean; bullets?: string[]; layout?: Layout };
type PageDef = { kicker: string; title: ReactNode; lede: string; accent?: string; heroLayout?: "split" | "rev" | "stacked"; window: ReactNode; windowLabel: string; primary?: [string, string]; secondary?: [string, string]; sections: Section[]; faq?: [string, string][]; cta?: { title: ReactNode; sub: string } };

function Hero({ p }: { p: PageDef }) {
  return <section className={`site-hero cx-hero accent-${p.accent || "lime"} hero-${p.heroLayout || "split"}`}>
    <div className="cx-hero-copy"><span className="cx-pill"><i />{p.kicker}</span><h1>{p.title}</h1><p>{p.lede}</p>
      <div className="cx-actions">{p.primary && <a className="lime" href={p.primary[1]}>{p.primary[0]} <span>→</span></a>}{p.secondary && <a className="ghost" href={p.secondary[1]}>{p.secondary[0]}</a>}</div></div>
    <div className="site-hero-window"><Frame label={p.windowLabel}>{p.window}</Frame></div>
  </section>;
}

function Sections({ list }: { list: Section[] }) {
  let splitCount = 0;
  return <>{list.map((s, i) => {
    let layout: Layout = s.layout || (s.aside ? (splitCount++ % 2 ? "rev" : "split") : "narrow");
    const copy = <div className="site-copy"><span className={`section-kicker ${s.dark ? "light" : ""}`}>{s.kicker}</span><h2>{s.title}</h2><div className="site-body">{s.body}</div>{s.bullets && <ul className="site-bullets">{s.bullets.map((b) => <li key={b}>{b}</li>)}</ul>}</div>;
    const aside = s.aside ? <div className="site-aside">{s.aside}</div> : null;
    return <section key={i} className={`site-section lay-${layout} ${s.dark ? "dark" : ""} ${i % 2 ? "alt" : ""}`}>
      <div className={`site-section-inner ${layout === "split" || layout === "rev" ? "" : "one"}`}>{layout === "rev" ? <>{aside}{copy}</> : <>{copy}{aside}</>}</div>
    </section>;
  })}</>;
}

function Faq({ items }: { items: [string, string][] }) {
  return <section className="site-section faq"><div className="site-section-inner one"><span className="section-kicker">QUESTIONS</span><h2>Straight answers.</h2><div className="faq-list">{items.map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>;
}

function Page({ p }: { p: PageDef }) {
  return <><Hero p={p} /><HonestyStrip /><Sections list={p.sections} />{p.faq && <Faq items={p.faq} />}<CtaBand {...(p.cta || {})} /></>;
}

/* ---------- small reusable asides ---------- */
const Stat = ({ n, l }: { n: string; l: string }) => <div className="stat"><strong>{n}</strong><small>{l}</small></div>;
const Cards = ({ items }: { items: [string, string, string?][] }) => <div className="mini-cards">{items.map(([t, d, h]) => h ? <a key={t} href={h} className="mini-card"><strong>{t}</strong><p>{d}</p><b>Learn more →</b></a> : <div key={t} className="mini-card"><strong>{t}</strong><p>{d}</p></div>)}</div>;
const Loop = () => <div className="loop-cards">{[["01", "Capture", "Invite from your website, CRM, POS, a partner, a building — or the not-ready pile you already paid for.", "paper"], ["02", "Check", "A consumer-permissioned soft check on three bureaus creates the starting point. MyScoreIQ.", "mint"], ["03", "Act", "Disputes by bureau, rent and bills reported, a plan in priority order. CreditBuilderIQ.", "lime"], ["04", "Return", "Program floors met, DTI in range → the consumer is asked, not you. Status returns to the original LO.", "dark"]].map(([n, t, d, tone]) => <article key={n} className={tone}><span>{n}</span><strong>{t}</strong><p>{d}</p></article>)}</div>;

/* ---------- pages ---------- */
const PAGES: Record<string, PageDef> = {
  "platform": { heroLayout: "stacked", kicker: "PLATFORM · HOW IT WORKS", title: <>A credit-readiness platform that lives <em>between</em> your systems.</>, lede: "ReadyIQ owns the consumer’s journey from “can I qualify?” to “review me,” runs the check / plan / dispute / build engine on IDIQ’s products, and sends status into whatever you already run. It is not a CRM, a score simulator or a counseling program.", accent: "teal", window: <FeedWindow />, windowLabel: "Organization portal · status feed", primary: ["Try the loan officer portal", DEMO + "?mode=lender&lpage=link"], secondary: ["Book a demo", "book-a-demo/"],
    sections: [
      { kicker: "ONE CONNECTED LOOP", title: <>From credit-challenged lead to <em>lender review.</em></>, body: <p>Four steps, one owner. ReadyIQ sits between your acquisition channels, the consumer’s credit tools and your mortgage systems — keeping ownership, consent and next steps clear at every step.</p>, aside: <Loop />, layout: "center" },
      { kicker: "THE CONTRACT", title: <>One status object. <em>Never a report.</em></>, body: <p>What flows into your CRM is a status object — pathway, round, next milestone, flags, attribution — and a handful of webhook events. Never a score, never a report, never tradelines. That is the whole integration surface, and it is why compliance says yes.</p>, bullets: ["readiness.trigger · review.requested · protect_mode.activated · progress.milestone_reached", "Attribution to the loan officer, branch, partner and source on every event", "Consumers can pause sharing — you get a paused status, nothing else"], aside: <Frame label="Integration hub · events"><EventsWindow /></Frame>, dark: true, layout: "rev" },
      { kicker: "NOT A CRM, ON PURPOSE", title: <>The CRM stays the <em>system of record.</em></>, body: <p>Notes, tasks, pipeline and campaigns stay in Total Expert, Shape or Salesforce. ReadyIQ sends status through Zapier or a native connector and asks for nothing back. Loan officers get one link and one read-only feed — no new queue to babysit.</p>, aside: <div className="stat-grid four"><Stat n="1" l="next action at a time" /><Stat n="1:1" l="loan officer attribution" /><Stat n="0" l="promised deletions, points or approvals" /><Stat n="3" l="bureaus, always" /></div>, layout: "band" },
      { kicker: "THE RAILS NOBODY ELSE HAS", title: <>Four rails, <em>one roof.</em></>, body: <p>Rent-reporting rails (CreditBuilderIQ / Resident-Link), monitoring and identity protection (MyScoreIQ), a dispute engine, and a lender network. Counseling networks have one. Consumer apps have two. Score simulators have none. The moves that matter — the Passport, renters starting early, the soft tri-merge last mile — exist because all four are under one roof.</p>, aside: <Cards items={[["Readiness Passport", "A verified, portable status the consumer owns.", "products/passport/"], ["Renters start early", "Property-manager links start rent history 12–24 months before a loan officer.", "partners/"], ["The soft tri-merge last mile", "Real mortgage-model scores at readiness, no hard pull.", "loan-officers/"]]} />, layout: "grid" },
    ],
    faq: [["Is ReadyIQ a CRM?", "No. It owns the consumer journey and sends status. Notes, tasks and pipeline stay where they are."], ["Do loan officers ever see the credit report?", "No. They see pathway, round, milestones and review requests. A review packet is status plus consent for the hard pull when they talk."], ["Are the scores mortgage scores?", "MyScoreIQ shows FICO® on three bureaus, labeled as not the mortgage-industry version. At readiness, a soft tri-merge via the lender’s vendor shows the real mortgage-model numbers without a hard inquiry."]] },

  "loan-officers": { kicker: "FOR LOAN OFFICERS", title: <>One link. <em>Zero busywork.</em></>, lede: "Sixty seconds to a link you can text, print or email. Everyone who uses it stays attributed to you. You see status, never their report — and when floors are met, the consumer is asked to come back to you.", accent: "teal", window: <LinkWindow />, windowLabel: "Your link · loan officer portal", primary: ["Get your link in 60 seconds", DEMO + "?mode=lender&lpage=start"], secondary: ["See the status feed", DEMO + "?mode=lender&lpage=borrowers"],
    sections: [
      { kicker: "60 SECONDS", title: <>Email and NMLS. <em>That’s the setup.</em></>, body: <p>We fill the rest from your NMLS ID and pull your company’s brand from its website. You get a link, a QR and a text you can send from your phone. No install, no training, no new queue.</p>, bullets: ["Text this to a client — one tap, attributed to you", "Print the QR on a card or an open-house flyer", "Invite by email with the same attribution"], aside: <Frame label="Status feed"><FeedWindow /></Frame> },
      { kicker: "THE LEADS YOU ALREADY PAID FOR", title: <>Lost-lead revival, <em>one button.</em></>, body: <p>Sync the not-ready pile from your CRM or drop a CSV. ReadyIQ de-dupes, keeps the original loan officer, and sends each person a personal invitation to their own front door. They consent themselves. You see status.</p>, aside: <div className="stat-grid four"><Stat n="214" l="not-ready leads matched" /><Stat n="173" l="personal invitations" /><Stat n="12" l="loan officers, attribution intact" /><Stat n="0" l="reports seen by anyone" /></div>, dark: true, layout: "band" },
      { kicker: "THE LAST MILE", title: <>Real mortgage scores — <em>soft.</em></>, body: <p>At readiness, your credit vendor can run a soft tri-merge with mortgage-model FICO® (2 · 4 · 5). The consumer sees the real numbers, you see “floors met,” and nobody’s credit takes a hard inquiry before you talk.</p>, aside: <Frame label="Review packet · soft tri-merge"><TriWindow /></Frame> },
    ],
    faq: [["What do I actually see?", "Pathway, round, next milestone, review requests, Protect Mode status. Never a score or a report unless the consumer shares it."], ["Where do my notes go?", "Your CRM. ReadyIQ sends status events through Zapier or a connector; it never asks you to work in a second system."], ["Can partners use it?", "Yes — realtors and property managers get their own links and QR; they see coarse status only."]] },

  "consumers": { heroLayout: "rev", kicker: "FOR CONSUMERS", title: <>Check, build, dispute — <em>long before you apply.</em></>, lede: "A private readiness check on three bureaus, a plan in priority order, disputes you approve one at a time, and rent that finally counts. Your loan officer sees status — never your report — and you can apply at any time. It’s never required.", accent: "mint", window: <ScoreWindow />, windowLabel: "Consumer portal · overview", primary: ["See the consumer portal", DEMO + "?mode=consumer&cpage=result"], secondary: ["Have a link from your lender? Start here", DEMO + "?c=summit-jlee"],
    sections: [
      { kicker: "THREE BUREAUS, HONESTLY", title: <>Always three scores, <em>never a promise.</em></>, body: <p>Equifax, Experian, TransUnion — FICO® via MyScoreIQ, labeled as not the version lenders pull. Every point that moves is tied to a cause. Nobody promises deletions, points or approvals.</p>, aside: <Frame label="Why it moved"><ScoreWindow /></Frame> },
      { kicker: "ONE CLEAR PATH", title: <>One next action, <em>every day.</em></>, body: <p>Utilization first, then the two flagged items, then 24 months of rent history — in the order an underwriter would care. Each step says why it matters for a mortgage. Ask ReadyIQ answers in plain words and never predicts an approval.</p>, aside: <Frame label="Ask ReadyIQ"><AskWindow /></Frame>, dark: true, layout: "center" },
      { kicker: "YOUR PASSPORT", title: <>A status you <em>own.</em></>, body: <p>Hand your readiness to a realtor or a second lender — your loan officer of record stays on every copy. It never contains your score or your report, and you can revoke it any time.</p>, aside: <Frame label="Readiness Passport"><PassportWindow /></Frame> },
    ],
    faq: [["Will this hurt my credit?", "No. The readiness check is a soft pull. A hard pull only happens when you request a review and say yes, when you talk to your loan officer."], ["Who sees what?", "Your loan officer sees status — pathway, round, milestones. Never your report or score details unless you request a review. Partners see even less."], ["¿Está en español?", "Sí — el portal, la puerta de entrada y el registro cambian a español con un toque."]] },

  "partners": { kicker: "FOR PARTNERS · REALTORS AND BUILDINGS", title: <>Agents and buildings <em>send people too.</em></>, lede: "Every partner gets a link and a QR. Realtors send buyers who aren’t ready yet; property managers start renters on 12–24 months of rent history before a loan officer is in the picture. Everyone stays attributed to the partner and the lender. Partners see coarse status only.", accent: "gold", window: <DoorWindow />, windowLabel: "A partner’s front door", primary: ["See the partners page", DEMO + "?mode=lender&lpage=partners"], secondary: ["Open a building’s door (Spanish)", DEMO + "?c=summit-palms&lang=es"],
    sections: [
      { kicker: "REALTORS", title: <>A stronger buyer, <em>months earlier.</em></>, body: <p>Your not-ready client gets a private plan and a loan officer who stays connected. You see “working” and “review requested” — never a score. When floors are met, the Readiness Passport is something they can bring to an offer.</p>, aside: <Frame label="Readiness Passport"><PassportWindow ready /></Frame> },
      { kicker: "PROPERTY MANAGERS", title: <>Rent that <em>counts.</em></>, body: <p>IDIQ already runs rent reporting for buildings. A building’s link starts residents reporting on-time rent to all three bureaus through CreditBuilderIQ — Fannie Mae’s DU counts it — and a lender is already connected when they’re ready to buy. The building sees nothing but “enrolled.”</p>, aside: <Frame label="Rent history"><BuildWindow /></Frame>, dark: true, layout: "center" },
    ],
    faq: [["What does a partner see?", "Sent · working · review requested. Never the score, never the report, never the plan."], ["Who is the loan officer of record?", "The lender who issued the partner link. Attribution is locked when the consumer enrolls."]] },

  "products/check": { kicker: "PRODUCT · CHECK", title: <>Three bureaus. <em>Honest numbers.</em></>, lede: "A consumer-permissioned soft check via MyScoreIQ: Equifax, Experian, TransUnion, FICO® — labeled for what it is. The starting point for every pathway, refreshed as the plan moves.", accent: "mint", window: <ScoreWindow />, windowLabel: "Three gauges · MyScoreIQ", primary: ["See it in the portal", DEMO + "?mode=consumer&cpage=result"],
    sections: [{ kicker: "PATHWAYS", title: <>Ready now · near ready · build · thin · <em>dispute.</em></>, body: <p>The check assigns a pathway in plain words and a round count (“round 2 of ~5”), not a readiness percentage. Program floors and an eligibility clock (Chapter 7, foreclosure, short sale) set honest expectations.</p>, aside: <div className="stat-grid four"><Stat n="3" l="bureaus, every time" /><Stat n="0" l="hard inquiries" /><Stat n="5" l="pathways" /><Stat n="1" l="next action" /></div>, layout: "band" }, { kicker: "WHY IT MOVED", title: <>Every point, <em>tied to a cause.</em></>, body: <p>+14 utilization down, +6 lates aging, −6 a new inquiry. Consumers stop guessing and loan officers stop explaining.</p>, dark: true }],
    faq: [["Is this a mortgage score?", "No, and the screen says so. At readiness a soft tri-merge through the lender’s vendor shows mortgage-model numbers without a hard pull."]] },

  "products/dispute-hub": { kicker: "PRODUCT · DISPUTE HUB", title: <>Find it. Dispute it. <em>Track it.</em></>, lede: "Negative items laid out by bureau — Equifax, Experian, TransUnion — and handled one at a time: is this right? → why not? → your letter → the clock. Mortgage-priority sequencing, paused automatically once a loan is in process. CreditBuilderIQ underneath.", accent: "violet", window: <BoardWindow />, windowLabel: "Negative items, by bureau", primary: ["Open the Dispute Hub", DEMO + "?mode=consumer&cpage=disputes"],
    sections: [{ kicker: "ONE ITEM AT A TIME", title: <>Is this information <em>right?</em></>, body: <p>Each item shows the facts, why CreditBuilderIQ flagged it, and why it matters for a mortgage — then one question. Say no and the letter writes itself; you read it and approve. Nothing is sent without you.</p>, bullets: ["Sequenced for a mortgage: collections that block programs first", "Letters only to the bureaus that actually report the item", "30-day clock kept for you; responses logged"] }, { kicker: "HONESTY", title: <>No promised <em>deletions.</em></>, body: <p>ReadyIQ does not claim accurate information can be removed or guarantee any result. Consumers dispute only what they believe is wrong — and the guideline notes explain when paying a collection does and doesn’t change the picture.</p>, dark: true }],
    faq: [["Does someone dispute for me?", "No — you drive. ReadyIQ writes the letter from your answers; you approve and it goes."], ["What happens during my loan?", "Protect Mode pauses new disputes so nothing changes on the report mid-underwriting."]] },

  "products/build-report": { kicker: "PRODUCT · BUILD & REPORT", title: <>Make the payments you already make <em>count.</em></>, lede: "Rent, electric, mobile — verified and reported to all three bureaus through CreditBuilderIQ, up to 24 months of history. Fannie Mae’s DU counts 12 months of on-time rent; thin files stop being thin.", accent: "lime", window: <BuildWindow />, windowLabel: "Rent history found", primary: ["See Build & report", DEMO + "?mode=consumer&cpage=reporting"],
    sections: [{ kicker: "RENT", title: <>24 months, <em>verified.</em></>, body: <p>CreditBuilderIQ matches the landlord, verifies the history and enrolls what the consumer chooses. Property-manager partners can start this a year before anyone talks to a lender.</p> }, { kicker: "EVERYDAY BILLS", title: <>Electric, mobile, <em>recurring.</em></>, body: <p>Eligible payments are matched, confirmed and added — no new traditional debt opened. Guidance on secured cards and credit-builder loans stays honest: check with your loan officer before opening or closing anything.</p>, dark: true }],
    faq: [["Is rent reporting guaranteed to raise my score?", "No. Results vary by product and scoring model; the screen says so. What it does is make verified history visible where it wasn’t."]] },

  "products/protect-mode": { kicker: "PRODUCT · PROTECT MODE", title: <>Ask before you act — <em>from application to closing.</em></>, lede: "The day a loan starts, Protect Mode pauses dispute suggestions, watches the report daily, alerts the loan officer as status, and reminds the consumer to call before opening, closing or paying off anything. Underwriters re-verify credit before closing; this is the window that blows up files.", accent: "teal", window: <ProtectWindow />, windowLabel: "Protect Mode · closing checklist", primary: ["See Protect Mode", DEMO + "?mode=consumer&cpage=guardian"],
    sections: [{ kicker: "WHAT CHANGES", title: <>Nothing — <em>on purpose.</em></>, body: <p>No new accounts, no big payoffs, no surprise inquiries. MyScoreIQ monitoring flags anything new the same day; the loan officer receives a status, not a report. Closing-fund wire reminders included.</p>, bullets: ["Disputes paused automatically", "Daily report watch via MyScoreIQ", "LOS milestone (Encompass) can switch it on"] }],
    faq: [["Does the loan officer get the alerts?", "As status — “new inquiry detected” — never the report."]] },

  "products/passport": { heroLayout: "rev", kicker: "PRODUCT · READINESS PASSPORT", title: <>Your readiness, <em>in your hands.</em></>, lede: "A portable, verified status the consumer owns and shares: pathway, floors met, DTI in range, rent months, disputes — and the loan officer of record on every copy. Never a score, never a report. When floors are met, it turns green: verified ready buyer.", accent: "lime", window: <PassportWindow ready />, windowLabel: "Readiness Passport · verified ready", primary: ["See the Passport", DEMO + "?mode=consumer&cpage=passport"], secondary: ["View a shared passport", DEMO + "?passport=RIQ-7F2A-MC"],
    sections: [{ kicker: "NETWORK EFFECT", title: <>The credential the whole transaction <em>trusts.</em></>, body: <p>Realtors strengthen offers with it; second lenders see status only; family can follow along. Attribution to the originating loan officer never moves. Only a platform neutral across lenders — and holding the credit-building rails — can issue it.</p> }, { kicker: "EARNED, NOT CLAIMED", title: <>Verified against <em>live status.</em></>, body: <p>The badge appears when program floors are met and DTI is in range, and disappears if they aren’t. Revocable by the consumer at any time.</p>, dark: true }],
    faq: [["Is the Passport a preapproval?", "No. It is status — verified by ReadyIQ, never a lending decision."]] },

  "products/ask": { kicker: "PRODUCT · ASK READYIQ", title: <>The underwriter <em>in your pocket.</em></>, lede: "Ask ReadyIQ knows the public FHA / Fannie / Freddie guidelines — collections thresholds, DTI treatment, rent history, the refresh before closing — and answers in plain words. It drafts letters of explanation in the consumer’s own voice. It never predicts an approval.", accent: "mint", window: <AskWindow />, windowLabel: "Ask ReadyIQ", primary: ["Try it in the portal", DEMO + "?mode=consumer&cpage=plan"],
    sections: [{ kicker: "GUIDELINE-AWARE", title: <>Why each step matters to an <em>underwriter.</em></>, body: <p>Every plan step carries a note: FHA’s $2,000 non-medical collections rule, pricing tiers for utilization, DU’s 12-month rent history, the credit refresh before closing. Guidance, not a promise — programs and overlays vary, and the loan officer has the final word.</p> }],
    faq: [["Does it give legal or lending advice?", "No. It summarizes public agency guidelines and drafts documents the consumer edits. Approvals are the lender’s call."]] },

  "integrations": { kicker: "INTEGRATIONS", title: <>One status object. <em>Every mortgage system.</em></>, lede: "Connections to Total Expert, Blend, Encompass, Shape, Salesforce and LenderHomePage. A status object, webhook events and a small API — three ways in, from a pasted link to a fully embedded front door.", accent: "teal", window: <EventsWindow />, windowLabel: "Live event stream", primary: ["Open the integration hub", DEMO + "?mode=integrations"],
    sections: [{ kicker: "THREE WAYS IN", title: <>Link · status feed · <em>embedded.</em></>, body: <p>Level 1: paste a link or QR anywhere. Level 2: Zapier / Make / native connectors push the status object into your CRM as fields and events. Level 3: the front door and consent live inside your site or POS, with SSO for loan officers.</p>, aside: <Cards items={[["Status object", "pathway · round · next milestone · flags · attribution", undefined], ["Webhook events", "readiness.trigger · review.requested · protect_mode.activated", undefined], ["API", "invitations · link resolution · status · webhooks · protect mode", undefined]]} />, layout: "grid" }],
    faq: [["Does ReadyIQ write into my CRM?", "Only status events you subscribe to. It never reads notes or tasks back."]] },

  "trust": { heroLayout: "stacked", kicker: "TRUST & COMPLIANCE", title: <>Built so compliance says <em>yes.</em></>, lede: "Consumer-permissioned, soft-pull only, status-never-reports, no promised outcomes, Reg B and TCPA language on the screens that need it. Every engine is named. Everything the consumer shares is theirs to revoke.", accent: "teal", window: <FeedWindow />, windowLabel: "What a loan officer sees",
    sections: [
      { kicker: "CONSENT MODEL", title: <>Three consents, <em>in plain words.</em></>, body: <p>Before any check: (1) let ReadyIQ pull my credit for my own review — soft, via MyScoreIQ and CreditBuilderIQ; (2) share my status — never my report — with my loan officer; (3) text me, with TCPA language and STOP. A fourth, separate consent covers the hard pull at review time, and it is captured for the conversation, not the platform.</p>, aside: <Frame label="The three consents · as the consumer sees them"><div className="consent-demo"><ConsentBlock onChange={() => {}} /></div></Frame>, layout: "rev" },
      { kicker: "WHAT NEVER LEAVES", title: <>Score, report, tradelines, SSN — <em>never shared.</em></>, body: <p>Loan officers and partners receive status objects. The Passport contains no score. Disputes are sent only with the consumer’s approval, and only to the bureaus that report the item. Consumers can pause sharing; the lender gets a paused status, nothing else.</p>, dark: true, bullets: ["Reg B line on every consumer screen: you can apply for a mortgage at any time — this is not required", "No readiness percentages, no promised deletions, points, approvals or timelines", "MyScoreIQ / CreditBuilderIQ named on every tool surface"], aside: <div className="stat-grid four"><Stat n="0" l="scores shared with a lender" /><Stat n="0" l="reports or tradelines leaving" /><Stat n="3" l="plain-English consents" /><Stat n="1" l="tap to revoke sharing" /></div>, layout: "band" },
      { kicker: "SECURITY", title: <>Bank-level encryption, <em>least privilege.</em></>, body: <p>Identity data is encrypted in transit and at rest and used only to complete the authorized soft check. Full SSN is never shared with the lender. Access is scoped by role — loan officer, branch, organization, partner — and every share and revoke is logged.</p> },
    ],
    faq: [["Is ReadyIQ a credit repair organization?", "The consumer drives every dispute and approves every letter; ReadyIQ provides tools and guidance and makes no outcome claims. Program terms are reviewed with counsel for each market."], ["How is the texting compliant?", "Opt-in with express consent language, message rates disclosure and STOP handling on the consent itself."]] },

  "resources": { kicker: "RESOURCES", title: <>Plain answers, <em>in one place.</em></>, lede: "The guide to what makes ReadyIQ a leader, the explainer loan officers send consumers about consumer scores vs. mortgage scores, and the questions we hear most.", accent: "mint", window: <AskWindow />, windowLabel: "Ask ReadyIQ", primary: ["Open the Guide", "resources/guide/"],
    sections: [{ kicker: "EXPLAINER", title: <>Consumer score vs. <em>mortgage score.</em></>, body: <p>MyScoreIQ shows FICO® 8 on three bureaus — great for building and disputing, and labeled as not the version lenders pull. Lenders use FICO® 2 / 4 / 5 on a tri-merge; the numbers differ. ReadyIQ closes the gap honestly: at readiness, a soft tri-merge through the lender’s vendor shows the real mortgage-model numbers, no hard inquiry.</p>, aside: <Frame label="Soft tri-merge"><TriWindow /></Frame> }, { kicker: "THE GUIDE", title: <>Eight moves only this combination of rails <em>makes possible.</em></>, body: <p>Readiness Passport · renters start early · the soft tri-merge last mile · the underwriter in your pocket · down-payment assistance at readiness · lost-lead revival · Spanish first-class · verified ready buyer.</p>, aside: <Cards items={[["The Guide", "Each move, where it lives, and why it matters.", "resources/guide/"], ["Try the live demo", "Website, loan officer portal, consumer portal, integration hub.", DEMO + "?mode=consumer&cpage=result"], ["Trust & compliance", "Consent model, what never leaves, security.", "trust/"]]} />, dark: true, layout: "grid" }],
    faq: [["Can I get a walkthrough?", "Yes — book a demo, or open the Guide and click through it yourself."]] },
};

/* ---------- special pages ---------- */
function GuidePage() {
  const items: [string, string, string][] = [["Readiness Passport", "The consumer owns a portable, verified status — hand it to a realtor or a second lender. The loan officer of record stays on every copy.", DEMO + "?mode=consumer&cpage=passport"], ["Renters start 12–24 months early", "Property managers get a partner link; renters begin reporting rent before a loan officer ever calls.", DEMO + "?mode=lender&lpage=partners"], ["The soft tri-merge last mile", "Real mortgage-model scores at readiness, no hard pull. Closes the “not a mortgage score” gap honestly.", DEMO + "?mode=consumer&cpage=result"], ["The underwriter in your pocket", "Every plan step says why it matters to an underwriter; Ask ReadyIQ knows the same guidelines.", DEMO + "?mode=consumer&cpage=plan"], ["Down-payment assistance at readiness", "Three programs the consumer may qualify for — confirmed by the LO, never awarded by us.", DEMO + "?mode=consumer&cpage=plan"], ["Lost-lead revival", "Sync the not-ready pile; every lead gets a personal invitation to the original LO’s front door.", DEMO + "?mode=lender&lpage=campaigns"], ["Spanish, first-class", "One toggle — front door, enrollment and overview switch to Spanish with the same honesty rules.", DEMO + "?c=summit-jlee&lang=es"], ["Verified ready buyer", "When floors are met the passport turns green — earned against live status, never claimed.", DEMO + "?mode=consumer&cpage=passport"]];
  return <><section className="site-hero cx-hero accent-lime"><div className="cx-hero-copy"><span className="cx-pill"><i />RESOURCES · THE GUIDE</span><h1>What makes it a <em>leader.</em></h1><p>Eight moves only this combination of rails makes possible. Each is one card or one button on a screen that already exists — click any of them to land on it in the live demo.</p><div className="cx-actions"><a className="lime" href={DEMO + "?guide=1"}>Open the guide inside the demo <span>→</span></a></div></div><div className="site-hero-window"><Frame label="Readiness Passport"><PassportWindow ready /></Frame></div></section>
    <HonestyStrip /><section className="site-section"><div className="site-section-inner one"><ol className="guide-grid">{items.map(([t, d, h], i) => <li key={t}><span>{String(i + 1).padStart(2, "0")}</span><strong>{t}</strong><p>{d}</p><a href={h}>Open in the demo →</a></li>)}</ol></div></section><CtaBand /></>;
}

function BookDemoPage() {
  const [sent, setSent] = useState(false);
  return <><section className="site-hero cx-hero accent-teal"><div className="cx-hero-copy"><span className="cx-pill"><i />BOOK A DEMO</span><h1>Thirty minutes. <em>Your leads, your CRM.</em></h1><p>We’ll walk the loop with your branding, show the status object landing in your CRM, and hand you a loan officer link to try on the spot.</p><div className="cx-actions"><a className="ghost" href={DEMO + "?mode=consumer&cpage=result"}>Or try the live demo now</a></div></div><div className="site-hero-window"><div className="demo-form">{!sent ? <><span className="section-kicker">TELL US WHO YOU ARE</span><div className="form-panel" style={{ padding: 0 }}><div className="form-grid"><label>Name<input defaultValue="" placeholder="Jordan Lee" /></label><label>Work email<input placeholder="jordan@summithomeloans.com" /></label><label>Company<input placeholder="Summit Home Loans" /></label><label>Role<select defaultValue="lo"><option value="lo">Loan officer</option><option>Branch manager</option><option>Marketing / growth</option><option>Compliance</option><option>Technology</option></select></label></div><label className="full-field">What would you like to see?<select defaultValue="all"><option value="all">The whole loop</option><option>Loan officer link and status feed</option><option>Consumer portal</option><option>CRM integration</option><option>Trust & compliance</option></select></label><button className="primary-lime wide dark-text" onClick={() => setSent(true)}>Request a demo <span>→</span></button><small>No pricing on the site — we talk about it on the call.</small></div></> : <div className="demo-sent"><span>✓</span><h3>Got it — we’ll reach out within one business day.</h3><p>Meanwhile, the live demo is open: the loan officer portal, the consumer portal and the integration hub.</p><a className="primary-dark" href={DEMO + "?mode=lender&lpage=link"}>Open the live demo →</a></div>}</div></div></section><HonestyStrip /><CtaBand title={<>Prefer to <em>click first?</em></>} sub="The whole product is live — website, loan officer portal, consumer portal, integration hub." /></>;
}

function SignInPage() {
  return <><section className="site-hero cx-hero accent-mint"><div className="cx-hero-copy"><span className="cx-pill"><i />SIGN IN</span><h1>Who’s <em>signing in?</em></h1><p>Loan officers and organizations sign in here. Consumers don’t need an account to start — use the link your loan officer sent you.</p></div><div className="site-hero-window"><div className="signin-cards"><a className="signin-card" href={DEMO + "?mode=lender&lpage=link"}><span className="section-kicker">LOAN OFFICER · ORGANIZATION</span><strong>Open the organization portal</strong><p>Your link, status feed, partners, journeys, integrations.</p><b>Sign in →</b></a><a className="signin-card" href={DEMO + "?c=summit-jlee"}><span className="section-kicker">CONSUMER</span><strong>Use the link your loan officer sent</strong><p>Or tap the QR on their card. Your front door is already branded and attributed.</p><b>Open my front door →</b></a><a className="signin-card ghost" href={DEMO + "?mode=lender&lpage=start"}><span className="section-kicker">NEW HERE?</span><strong>Get your link in 60 seconds</strong><p>Email and NMLS. We fill in the rest.</p><b>Start →</b></a></div></div></section><HonestyStrip /><SiteFooterSpacer /></>;
}
function SiteFooterSpacer() { return <div style={{ height: 24 }} />; }

function HomePage() {
  const to = (href: string) => () => { location.href = href; };
  return <div className="site-home"><ReadyIQWebsite openOrganization={to(DEMO + "?mode=lender&lpage=link")} openStart={to(DEMO + "?mode=lender&lpage=start")} openConsumer={(page = "welcome") => { location.href = page === "welcome" ? DEMO + "?mode=consumer" : DEMO + "?mode=consumer&cpage=" + page; }} openIntegrations={to("integrations/")} />
    <section className="site-section"><div className="site-section-inner one"><span className="section-kicker">EXPLORE</span><h2>Go deeper on <em>any of it.</em></h2><div className="mini-cards four">{([["Platform", "The loop, the status object, not a CRM.", "platform/"], ["For loan officers", "One link, sixty seconds, status only.", "loan-officers/"], ["For consumers", "Check, build, dispute — before you apply.", "consumers/"], ["Trust & compliance", "Consent model, what never leaves, security.", "trust/"]] as [string, string, string][]).map(([t, d, h]) => <a key={t} href={h} className="mini-card"><strong>{t}</strong><p>{d}</p><b>Explore →</b></a>)}</div></div></section>
  </div>;
}

export function Site({ route }: { route: Route }) {
  const key = route.replace(/\/$/, "");
  let body: ReactNode;
  if (key === "") body = <HomePage />;
  else if (key === "resources/guide") body = <GuidePage />;
  else if (key === "book-a-demo") body = <BookDemoPage />;
  else if (key === "sign-in") body = <SignInPage />;
  else if (key === "integrations") body = <><Page p={PAGES.integrations} /><div className="site-hub"><IntegrationHub setMode={() => { location.href = DEMO + "?mode=lender&lpage=link"; }} /></div></>;
  else if (PAGES[key]) body = <Page p={PAGES[key]} />;
  else body = <section className="site-section"><div className="site-section-inner one"><h2>Page not found.</h2><p><a href="./">Back to the start →</a></p></div></section>;
  return <div className="site"><SiteNav route={key} /><main>{body}</main><SiteFooter /></div>;
}
